In [3]:
from src.Games.TicTacToe.TicTacToe import TicTacToe_Game, TicTacToe_Action
from src.players.Input.terminalInput import terminalPlayer as humanPlayer
from src.players.MCTS.Models.MCTS_uct import MCTS_uct_Tree
from src.players.MCTS.Models.Alpha_Zero import Alpha_Zero_player, AZ_search_args, AZ_NArgs, AZ_train_args
from src.players.MCTS.Models.ML_architecture.resnet import BaseResnet
from src.players.MCTS.Treeplayer import SArgs
from src.base import play, bind, Piece, Role, Move
import time
from copy import deepcopy
import numpy as np
from typing import Any
import torch
import os
import math

from src.UI.GUI import pygame_play

pygame 2.6.0 (SDL 2.28.4, Python 3.12.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:

game = TicTacToe_Game()
pygame_play(game)

(1, 1)
(0, 1)
(0, 0)
(1, 0)
(2, 2)


test play

In [ ]:
# play(TicTacToe_Game(), [humanPlayer(TicTacToe_Game(), "X"), humanPlayer(TicTacToe_Game(), "O")])

test board

In [2]:

# game = TicTacToe_Game()

# print(game.encode())

# game.make_move(TicTacToe_move("0,0"))

# print(game.encode())
# print(game.curr_role)

# game.unmake_move()

# print(game.encode())
# print(game.curr_role)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
O


AttributeError: 'TicTacToe_Game' object has no attribute 'players'

test pygame

In [1]:
# from src.UI.GUI import pygame_play

# pygame_play()

pygame 2.6.0 (SDL 2.28.4, Python 3.12.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
# game = TicTacToe_Game()

# game.make_move(TicTacToe_move("0,0"))

# print(game.roles[0].pieces)

[X]


In [ ]:
# def draw_X(screen, pos, step):
#     center = (step * (pos[0] + 1) / 2, step * (pos[1] + 1) / 2)
    
#     pygame.draw.line(screen, (255, 255, 255), (center[0] - 100, center[1] - 100), (center[0] + 100, center[1] + 100), 8)
#     pygame.draw.line(screen, (255, 255, 255), (center[0] - 100, center[1] + 100), (center[0] + 100, center[1] - 100), 8)

# def draw_O(screen, pos, step):
#     pygame.draw.circle(screen, (255, 255, 255), (step * (pos[0] + 1) / 2, step * (pos[1] + 1) / 2), 100, 10)

# def pygame_play():
#     window_len = 800
#     SCREEN_WIDTH = window_len
#     SCREEN_HEIGHT = window_len
#     FPS = 10
#     pygame.init()
#     screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
#     clock = pygame.time.Clock()

#     game = TicTacToe_Game()

#     # game.make_move(TicTacToe_move("0,0"))

#     pygame.display.set_caption("Tic Tac Toe")

#     po = False
#     running = True
#     while running:

#         screen.fill((0, 0, 0))
#         step = window_len / 3

#         pygame.draw.line(screen, (255, 255, 255), (0, step), (window_len, step), 10)
#         pygame.draw.line(screen, (255, 255, 255), (0, step * 2), (window_len, step * 2), 10)

#         pygame.draw.line(screen, (255, 255, 255), (step, 0), (step, window_len), 10)
#         pygame.draw.line(screen, (255, 255, 255), (step * 2, 0), (step * 2, window_len), 10)

        
#         for piece in game.roles[0].pieces:
#             draw_X(screen, piece.location, step)

#         for piece in game.roles[1].pieces:
#             draw_O(screen, piece.location, step)

#         for event in pygame.event.get():
#             if event.type == pygame.QUIT:
#                 running = False
#             elif event.type == pygame.MOUSEBUTTONDOWN:
#                 pos = pygame.mouse.get_pos()
#                 print(pos)
#                 game.make_move(TicTacToe_move(str(pos[0] + ', ' + pos[1])))

#         pygame.display.update()
#         clock.tick(FPS)

#     pygame.quit()

# pygame_play()